apiVersion: v1
kind: Service
metadata:
  name: {{ include "default.fullname" . }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  externalTrafficPolicy: Local
  selector:
    {{- include "default.selectorLabels" . | nindent 4 }}
    app: app
